<?php script("article-list.js") ?>
<div class="article-list">
<h1 class="title">Article list</h1>
<div class="articles" id="data" data-ids="<?php json(array_map(fn ($article) => $article->id, $articles)) ?>">
    <?php foreach ($articles as $article): ?>
        <div class="article" id="article-<?= $article->id ?>">
        <div>
        <h2 class="header"> <?= $article->name ?> </h2>
            <div class="buttons">
            <a role="button" class="button" href="<?= url('article/'.  $article->id) ?>">Show</a>
            <a role="button" class="button" href="<?= url('article-edit/'.  $article->id) ?>">Edit</a>
            <div  role="button" class="button button-red" onclick="deleteArticle(<?= $article->id ?>)">Delete
                    </div>
            </div>
        </div>
            
        </div>
    <?php endforeach; ?>
</div>
<div class="controls">
    <div class="paginator">
        <button class="button" id="paginator-prev">Previous page</button>
        <button class="button" id="paginator-next">Next page</button>
        <div>Page count <span id="paginator-counter"></span></div>
    </div>
    <div>
        <button  class="button button-blue" id="create-button" >Create new article</button>
    </div>
</div>
</div>

<div class="overlay" id="overlay">

<form method="POST" action="<?php url('article-create') ?>" class="modal">
    <div class="control">
        <label for="name-input">Name</label>
        <input type="text" id="name-input" name="name"  maxlength="32" required  />
    </div>
    <div class="buttons">
        <button class="button" id="close-button" type="button">
            Cancel 
        </button>
        <button class="button button-blue" type="submit" id="submit-button">
            Create 
        </button>

    </div>
</form>
</div>
