<!-- {{ INHERITS:base }} -->

<form class="article-edit" method="post" id="my-form">
    <div class="control">
        <label for="name-input">Name</label>
        <input type="text" id="name-input" name="name" maxlength="32" value="<?=$article->name?>" required  />
    </div>

    <div class="control">
        <label>Content</label>
        <textarea name="content" maxlength="1024" ><?= $article->content ?></textarea>
    </div>

    <div class="buttons">
        <button class="button button-green" type="submit" id="submit-button">Save</button>
        <a role="button" class="button button-red" href="articles">Back to articles</a>
    </div>
    <script>
        document.getElementById("my-form").addEventListener("input", function () {
            document.getElementById("submit-button").disabled =
                document.getElementById("name-input").value.length === 0;
        });
    </script>
</form>
