<?php

$db = include('db.php');


$values = <<<EOD
("In 10 Minutes, I'll Give You The", "This is a test article. Cats are the best"),
("WASTE OF TIME Adventures", "This is a test article. Cats are the best"),
("How To Start A Business With WAS", "This is a test article. Cats are the best"),
("5 Sexy Ways To Improve Your WAST", "This is a test article. Cats are the best"),
("Marriage And WASTE OF TIME Have ", "This is a test article. Cats are the best"),
("The Untold Secret To WASTE OF TI", "This is a test article. Cats are the best"),
("Here Is A Method That Is Helping", "This is a test article. Cats are the best"),
("The Secret Of WASTE OF TIME", "This is a test article. Cats are the best"),
("5 Surefire Ways WASTE OF TIME Wi", "This is a test article. Cats are the best"),
("How You Can (Do) WASTE OF TIME I", "This is a test article. Cats are the best"),
("What Can You Do About WASTE OF T", "This is a test article. Cats are the best"),
("How To Make Your WASTE OF TIME L", "This is a test article. Cats are the best"),
("Short Story: The Truth About WAS", "This is a test article. Cats are the best"),
("Who Else Wants To Know The Myste", "This is a test article. Cats are the best"),
("No More Mistakes With WASTE OF T", "This is a test article. Cats are the best"),
("Essential WASTE OF TIME Smartpho", "This is a test article. Cats are the best"),
("This Study Will Perfect Your WAS", "This is a test article. Cats are the best"),
("What Alberto Savoia Can Teach Yo", "This is a test article. Cats are the best"),
("5 Secrets: How To Use WASTE OF T", "This is a test article. Cats are the best"),
("WASTE OF TIME An Incredibly Easy", "This is a test article. Cats are the best"),
("The Truth Is You Are Not The Onl", "This is a test article. Cats are the best"),
("How To Sell WASTE OF TIME", "This is a test article. Cats are the best"),
("3 Ways To Master WASTE OF TIME W", "This is a test article. Cats are the best"),
("Proof That WASTE OF TIME Is Exac", "This is a test article. Cats are the best"),
("3 Ways Create Better WASTE OF TI", "This is a test article. Cats are the best"),
("The Philosophy Of WASTE OF TIME", "This is a test article. Cats are the best"),
("Being A Star In Your Industry Is", "This is a test article. Cats are the best"),
("Are You Making These WASTE OF TI", "This is a test article. Cats are the best"),
("How To Handle Every WASTE OF TIM", "This is a test article. Cats are the best"),
("Does WASTE OF TIME Sometimes Mak", "This is a test article. Cats are the best"),
("The Death Of WASTE OF TIME And H", "This is a test article. Cats are the best"),
("Why My WASTE OF TIME Is Better T", "This is a test article. Cats are the best"),
("Don't Be Fooled By WASTE OF TIME", "This is a test article. Cats are the best"),
("Find A Quick Way To WASTE OF TIM", "This is a test article. Cats are the best"),
("10 Unforgivable Sins Of WASTE OF", "This is a test article. Cats are the best"),
("Turn Your WASTE OF TIME Into A H", "This is a test article. Cats are the best"),
("Got Stuck? Try These Tips To Str", "This is a test article. Cats are the best"),
("Learn Exactly How I Improved WAS", "This is a test article. Cats are the best"),
("The Quickest & Easiest Way To WA", "This is a test article. Cats are the best"),
("Why Everything You Know About WA", "This is a test article. Cats are the best"),
("Apply These 5 Secret Techniques ", "This is a test article. Cats are the best"),
("10 Ways To Reinvent Your WASTE O", "This is a test article. Cats are the best"),
("Wondering How To Make Your WASTE", "This is a test article. Cats are the best"),
("15 Tips For WASTE OF TIME Succes", "This is a test article. Cats are the best"),
("3 WASTE OF TIME Secrets You Neve", "This is a test article. Cats are the best"),
("What Everyone Must Know About WA", "This is a test article. Cats are the best"),
("WASTE OF TIME And Love Have 4 Th", "This is a test article. Cats are the best"),
("Get The Most Out of WASTE OF TIM", "This is a test article. Cats are the best"),
("10 Tips That Will Make You Influ", "This is a test article. Cats are the best"),
("Double Your Profit With These 5 ", "This is a test article. Cats are the best"),
("These 5 Simple WASTE OF TIME Tri", "This is a test article. Cats are the best"),
("WASTE OF TIME Strategies For Beg", "This is a test article. Cats are the best"),
("The Ugly Truth About WASTE OF TI", "This is a test article. Cats are the best"),
("Get Better WASTE OF TIME Results", "This is a test article. Cats are the best"),
("To People That Want To Start WAS", "This is a test article. Cats are the best"),
("Who Else Wants To Be Successful ", "This is a test article. Cats are the best"),
("SuperEasy Ways To Learn Everythi", "This is a test article. Cats are the best"),
("Learn Exactly How We Made WASTE ", "This is a test article. Cats are the best"),
("World Class Tools Make WASTE OF ", "This is a test article. Cats are the best"),
("10 Best Practices For WASTE OF T", "This is a test article. Cats are the best"),
("What Can Instagramm Teach You Ab", "This is a test article. Cats are the best"),
("WASTE OF TIME Expert Interview", "This is a test article. Cats are the best"),
("Best WASTE OF TIME Android/iPhon", "This is a test article. Cats are the best"),
("52 Ways To Avoid WASTE OF TIME B", "This is a test article. Cats are the best"),
("The A - Z Guide Of WASTE OF TIME", "This is a test article. Cats are the best"),
("What You Can Learn From Bill Gat", "This is a test article. Cats are the best"),
("3 Ways You Can Reinvent WASTE OF", "This is a test article. Cats are the best"),
("The Secret of WASTE OF TIME", "This is a test article. Cats are the best"),
("The Lazy Way To WASTE OF TIME", "This is a test article. Cats are the best"),
("3 Tips About WASTE OF TIME You C", "This is a test article. Cats are the best"),
("How To Turn Your WASTE OF TIME F", "This is a test article. Cats are the best"),
("Why Some People Almost Always Ma", "This is a test article. Cats are the best"),
("Where Can You Find Free WASTE OF", "This is a test article. Cats are the best"),
("WASTE OF TIME? It's Easy If You ", "This is a test article. Cats are the best"),
("7 Easy Ways To Make WASTE OF TIM", "This is a test article. Cats are the best"),
("5 Easy Ways You Can Turn WASTE O", "This is a test article. Cats are the best"),
("9 Ways WASTE OF TIME Can Make Yo", "This is a test article. Cats are the best"),
("What You Should Have Asked Your ", "This is a test article. Cats are the best"),
("Need More Time? Read These Tips ", "This is a test article. Cats are the best"),
("Why You Never See WASTE OF TIME ", "This is a test article. Cats are the best"),
("Make Your WASTE OF TIMEA Reality", "This is a test article. Cats are the best"),
("15 Lessons About WASTE OF TIME Y", "This is a test article. Cats are the best"),
("9 Ridiculous Rules About WASTE O", "This is a test article. Cats are the best"),
("Remarkable Website - WASTE OF TI", "This is a test article. Cats are the best"),
("The Ultimate Secret Of WASTE OF ", "This is a test article. Cats are the best"),
("The Untold Secret To Mastering W", "This is a test article. Cats are the best"),
("The Truth About WASTE OF TIME In", "This is a test article. Cats are the best"),
("The WASTE OF TIME Mystery Reveal", "This is a test article. Cats are the best"),
("How To Quit WASTE OF TIME In 5 D", "This is a test article. Cats are the best"),
("WASTE OF TIME Your Way To Succes", "This is a test article. Cats are the best"),
("Top 10 Tips To Grow Your WASTE O", "This is a test article. Cats are the best"),
("The Anthony Robins Guide To WAST", "This is a test article. Cats are the best"),
("7 Ways To Keep Your WASTE OF TIM", "This is a test article. Cats are the best"),
("How To Win Buyers And Influence ", "This is a test article. Cats are the best"),
("The Next 3 Things To Immediately", "This is a test article. Cats are the best"),
("Winning Tactics For WASTE OF TIM", "This is a test article. Cats are the best"),
("Master (Your) WASTE OF TIME in 5", "This is a test article. Cats are the best"),
("Everything You Wanted to Know Ab", "This is a test article. Cats are the best"),
("Never Changing WASTE OF TIME Wil", "This is a test article. Cats are the best"),
("How To Teach WASTE OF TIME Bette", "This is a test article. Cats are the best"),
("Congratulations! Your WASTE OF T", "This is a test article. Cats are the best"),
("Here Is A Quick Cure For WASTE O", "This is a test article. Cats are the best"),
("WASTE OF TIME Smackdown!", "This is a test article. Cats are the best"),
("Where Is The Best WASTE OF TIME?", "This is a test article. Cats are the best"),
("Should Fixing WASTE OF TIME Take", "This is a test article. Cats are the best"),
("10 Warning Signs Of Your WASTE O", "This is a test article. Cats are the best"),
("Why You Really Need (A) WASTE OF", "This is a test article. Cats are the best"),
("If You Do Not (Do)WASTE OF TIME ", "This is a test article. Cats are the best"),
("5 Ways To Get Through To Your WA", "This is a test article. Cats are the best"),
("Read This Controversial Article ", "This is a test article. Cats are the best"),
("Who Else Wants To Enjoy WASTE OF", "This is a test article. Cats are the best"),
("Avoid The Top 10 WASTE OF TIME M", "This is a test article. Cats are the best"),
("Death, WASTE OF TIME And Taxes", "This is a test article. Cats are the best"),
("13 Myths About WASTE OF TIME", "This is a test article. Cats are the best"),
("How To Deal With(A) Very Bad WAS", "This is a test article. Cats are the best"),
("How To Lose Money With WASTE OF ", "This is a test article. Cats are the best"),
("The Ultimate Guide To WASTE OF T", "This is a test article. Cats are the best"),
("How To Improve At WASTE OF TIME ", "This is a test article. Cats are the best"),
("Interesting Facts I Bet You Neve", "This is a test article. Cats are the best"),
("WASTE OF TIME Shortcuts - The Ea", "This is a test article. Cats are the best"),
("Fall In Love With WASTE OF TIME", "This is a test article. Cats are the best"),
("Fascinating WASTE OF TIME Tactic", "This is a test article. Cats are the best"),
("The Number One Reason You Should", "This is a test article. Cats are the best"),
("How To Find The Right WASTE OF T", "This is a test article. Cats are the best"),
("Get Rid of WASTE OF TIME For Goo", "This is a test article. Cats are the best"),
("17 Tricks About WASTE OF TIME Yo", "This is a test article. Cats are the best"),
("The Secret of Successful WASTE O", "This is a test article. Cats are the best"),
("Now You Can Have The WASTE OF TI", "This is a test article. Cats are the best"),
("5 Best Ways To Sell WASTE OF TIM", "This is a test article. Cats are the best"),
("Open The Gates For WASTE OF TIME", "This is a test article. Cats are the best"),
("How To Become Better With WASTE ", "This is a test article. Cats are the best"),
("Sick And Tired Of Doing WASTE OF", "This is a test article. Cats are the best"),
("How I Improved My WASTE OF TIME ", "This is a test article. Cats are the best"),
("Why Most People Will Never Be Gr", "This is a test article. Cats are the best"),
("22 Tips To Start Building A WAST", "This is a test article. Cats are the best"),
("Listen To Your Customers. They W", "This is a test article. Cats are the best"),
("7 and a Half Very Simple Things ", "This is a test article. Cats are the best"),
("Do WASTE OF TIME Better Than Bar", "This is a test article. Cats are the best"),
("Best Make WASTE OF TIME You Will", "This is a test article. Cats are the best"),
("10 Ways To Immediately Start Sel", "This is a test article. Cats are the best"),
("Cracking The WASTE OF TIME Code", "This is a test article. Cats are the best"),
("Believe In Your WASTE OF TIME Sk", "This is a test article. Cats are the best"),
("Sexy WASTE OF TIME", "This is a test article. Cats are the best"),
("Now You Can Buy An App That is R", "This is a test article. Cats are the best"),
("Stop Wasting Time And Start WAST", "This is a test article. Cats are the best"),
("Savvy|Smart|Sexy People Do WASTE", "This is a test article. Cats are the best"),
("Secrets To WASTE OF TIME – Eve", "This is a test article. Cats are the best"),
("Learn To (Do) WASTE OF TIME Like", "This is a test article. Cats are the best"),
("I Don't Want To Spend This Much ", "This is a test article. Cats are the best"),
("5 Incredibly Useful WASTE OF TIM", "This is a test article. Cats are the best"),
("Lies And Damn Lies About WASTE O", "This is a test article. Cats are the best"),
("Rules Not To Follow About WASTE ", "This is a test article. Cats are the best"),
("WASTE OF TIME - So Simple Even Y", "This is a test article. Cats are the best"),
("WASTE OF TIME: This Is What Prof", "This is a test article. Cats are the best"),
("Why Ignoring WASTE OF TIME Will ", "This is a test article. Cats are the best"),
("Get Rid of WASTE OF TIME Once an", "This is a test article. Cats are the best"),
("2 Things You Must Know About WAS", "This is a test article. Cats are the best"),
("Ho To (Do) WASTE OF TIME Without", "This is a test article. Cats are the best"),
("Why WASTE OF TIME Is No Friend T", "This is a test article. Cats are the best"),
("WASTE OF TIME Is Essential For Y", "This is a test article. Cats are the best"),
("4 Ways You Can Grow Your Creativ", "This is a test article. Cats are the best"),
("How To Teach WASTE OF TIME Like ", "This is a test article. Cats are the best"),
("Answered: Your Most Burning Ques", "This is a test article. Cats are the best"),
("Find Out How I Cured My WASTE OF", "This is a test article. Cats are the best"),
("Fast-Track Your WASTE OF TIME", "This is a test article. Cats are the best"),
("15 Unheard Ways To Achieve Great", "This is a test article. Cats are the best"),
("3 Easy Ways To Make WASTE OF TIM", "This is a test article. Cats are the best"),
("You Don't Have To Be A Big Corpo", "This is a test article. Cats are the best"),
("How To Take The Headache Out Of ", "This is a test article. Cats are the best"),
("Beware The WASTE OF TIME Scam", "This is a test article. Cats are the best"),
("Take The Stress Out Of WASTE OF ", "This is a test article. Cats are the best"),
("Clear And Unbiased Facts About W", "This is a test article. Cats are the best"),
("Why Most WASTE OF TIME Fail", "This is a test article. Cats are the best"),
("You Will Thank Us - 10 Tips Abou", "This is a test article. Cats are the best"),
("You Can Thank Us Later - 3 Reaso", "This is a test article. Cats are the best"),
("3 Simple Tips For Using WASTE OF", "This is a test article. Cats are the best"),
("What Your Customers Really Think", "This is a test article. Cats are the best"),
("Guaranteed No Stress WASTE OF TI", "This is a test article. Cats are the best"),
("Want A Thriving Business? Focus ", "This is a test article. Cats are the best"),
("How To Get (A) Fabulous WASTE OF", "This is a test article. Cats are the best"),
("Top 25 Quotes On WASTE OF TIME", "This is a test article. Cats are the best"),
("At Last, The Secret To WASTE OF ", "This is a test article. Cats are the best"),
("5 Problems Everyone Has With WAS", "This is a test article. Cats are the best"),
("Is WASTE OF TIME Worth [$] To Yo", "This is a test article. Cats are the best"),
("Little Known Ways To Rid Yoursel", "This is a test article. Cats are the best"),
("Don't Fall For This WASTE OF TIM", "This is a test article. Cats are the best"),
("Revolutionize Your WASTE OF TIME", "This is a test article. Cats are the best"),
("How You Can (Do) WASTE OF TIME A", "This is a test article. Cats are the best"),
("WASTE OF TIME: What A Mistake!", "This is a test article. Cats are the best"),
("Using 7 WASTE OF TIME Strategies", "This is a test article. Cats are the best"),
("WASTE OF TIME And Love - How The", "This is a test article. Cats are the best"),
("How To Turn WASTE OF TIME Into S", "This is a test article. Cats are the best"),
("Why I Hate WASTE OF TIME", "This is a test article. Cats are the best"),
("Proof That WASTE OF TIME Really ", "This is a test article. Cats are the best"),
("The Best Way To WASTE OF TIME", "This is a test article. Cats are the best"),
("How To Learn WASTE OF TIME", "This is a test article. Cats are the best"),
("10 Things You Have In Common Wit", "This is a test article. Cats are the best"),
("Fear? Not If You Use WASTE OF TI", "This is a test article. Cats are the best"),
("How To Make More WASTE OF TIME B", "This is a test article. Cats are the best"),
("It's All About (The) WASTE OF TI", "This is a test article. Cats are the best"),
("WASTE OF TIME: Do You Really Nee", "This is a test article. Cats are the best"),
("If You Want To Be A Winner, Chan", "This is a test article. Cats are the best"),
("Here's A Quick Way To Solve A Pr", "This is a test article. Cats are the best"),
("Want More Money? Start WASTE OF ", "This is a test article. Cats are the best"),
("Can You Really Find WASTE OF TIM", "This is a test article. Cats are the best"),
("How To Earn $398/Day Using WASTE", "This is a test article. Cats are the best"),
("WASTE OF TIME Works Only Under T", "This is a test article. Cats are the best"),
("How We Improved Our WASTE OF TIM", "This is a test article. Cats are the best"),
("The Hidden Mystery Behind WASTE ", "This is a test article. Cats are the best"),
("11 Methods Of WASTE OF TIME Domi", "This is a test article. Cats are the best"),
("How To Use WASTE OF TIME To Desi", "This is a test article. Cats are the best"),
("7 Rules About WASTE OF TIME Mean", "This is a test article. Cats are the best"),
("10 Secret Things You Didn't Know", "This is a test article. Cats are the best"),
("How I Improved My WASTE OF TIME ", "This is a test article. Cats are the best"),
("101 Ideas For WASTE OF TIME", "This is a test article. Cats are the best"),
("How To Make Your Product Stand O", "This is a test article. Cats are the best"),
("The Lazy Man's Guide To WASTE OF", "This is a test article. Cats are the best"),
("What Everyone Ought To Know Abou", "This is a test article. Cats are the best"),
("Quick and Easy Fix For Your WAST", "This is a test article. Cats are the best"),
("Can You Pass The WASTE OF TIME T", "This is a test article. Cats are the best"),
("If WASTE OF TIME Is So Terrible,", "This is a test article. Cats are the best"),
("5 Things To Do Immediately About", "This is a test article. Cats are the best"),
("Never Suffer From WASTE OF TIME ", "This is a test article. Cats are the best"),
("WASTE OF TIME: An Incredibly Eas", "This is a test article. Cats are the best"),
("WASTE OF TIME Iphone Apps", "This is a test article. Cats are the best"),
("5 Brilliant Ways To Use WASTE OF", "This is a test article. Cats are the best"),
("WASTE OF TIME Made Simple - Even", "This is a test article. Cats are the best"),
("Little Known Ways to WASTE OF TI", "This is a test article. Cats are the best"),
("5 Simple Steps To An Effective W", "This is a test article. Cats are the best"),
("How To Start WASTE OF TIME With ", "This is a test article. Cats are the best"),
("What Zombies Can Teach You About", "This is a test article. Cats are the best"),
("A Surprising Tool To Help You WA", "This is a test article. Cats are the best"),
("The Secrets To WASTE OF TIME", "This is a test article. Cats are the best"),
("Best 50 Tips For WASTE OF TIME", "This is a test article. Cats are the best"),
("5 Reasons WASTE OF TIME Is A Was", "This is a test article. Cats are the best"),
("Find Out Now, What Should You Do", "This is a test article. Cats are the best"),
("Why WASTE OF TIME Is The Only Sk", "This is a test article. Cats are the best"),
("3 Things Everyone Knows About WA", "This is a test article. Cats are the best"),
("What Can You Do To Save Your WAS", "This is a test article. Cats are the best"),
("WASTE OF TIME: The Samurai Way", "This is a test article. Cats are the best"),
("Picture Your WASTE OF TIME On To", "This is a test article. Cats are the best"),
("Take 10 Minutes to Get Started W", "This is a test article. Cats are the best"),
("Improve(Increase) Your WASTE OF ", "This is a test article. Cats are the best"),
("Here Is What You Should Do For Y", "This is a test article. Cats are the best"),
("Old School WASTE OF TIME", "This is a test article. Cats are the best"),
("Succeed With WASTE OF TIME In 24", "This is a test article. Cats are the best"),
("3 Mistakes In WASTE OF TIME That", "This is a test article. Cats are the best"),
("Warning: These 9 Mistakes Will D", "This is a test article. Cats are the best"),
("WASTE OF TIME Is Crucial To Your", "This is a test article. Cats are the best"),
("10 Funny WASTE OF TIME Quotes", "This is a test article. Cats are the best"),
("3 Ways To Have (A) More Appealin", "This is a test article. Cats are the best"),
("The WASTE OF TIME That Wins Cust", "This is a test article. Cats are the best"),
("A Guide To WASTE OF TIME At Any ", "This is a test article. Cats are the best"),
("WASTE OF TIME Is Bound To Make A", "This is a test article. Cats are the best"),
("Have You Heard? WASTE OF TIME Is", "This is a test article. Cats are the best"),
("The Single Most Important Thing ", "This is a test article. Cats are the best"),
("The Secrets To Finding World Cla", "This is a test article. Cats are the best"),
("Want To Step Up Your WASTE OF TI", "This is a test article. Cats are the best"),
("Some People Excel At WASTE OF TI", "This is a test article. Cats are the best"),
("Don't Just Sit There! Start WAST", "This is a test article. Cats are the best"),
("The Ultimate Deal On WASTE OF TI", "This is a test article. Cats are the best"),
("Everything You Wanted to Know Ab", "This is a test article. Cats are the best"),
("How To Win Friends And Influence", "This is a test article. Cats are the best"),
("The Biggest Lie In WASTE OF TIME", "This is a test article. Cats are the best"),
("Boost Your WASTE OF TIME With Th", "This is a test article. Cats are the best"),
("Top 10 Tips With WASTE OF TIME", "This is a test article. Cats are the best"),
("27 Ways To Improve WASTE OF TIME", "This is a test article. Cats are the best"),
("Are You Embarrassed By Your WAST", "This is a test article. Cats are the best"),
("5 Actionable Tips on WASTE OF TI", "This is a test article. Cats are the best"),
("How To Win Clients And Influence", "This is a test article. Cats are the best"),
("OMG! The Best WASTE OF TIME Ever", "This is a test article. Cats are the best"),
("5 Ways You Can Get More WASTE OF", "This is a test article. Cats are the best"),
("5 Brilliant Ways To Teach Your A", "This is a test article. Cats are the best"),
("2 Ways You Can Use WASTE OF TIME", "This is a test article. Cats are the best"),
("How WASTE OF TIME Made Me A Bett", "This is a test article. Cats are the best"),
("12 Questions Answered About WAST", "This is a test article. Cats are the best"),
("The Untapped Gold Mine Of WASTE ", "This is a test article. Cats are the best"),
("There’s Big Money In WASTE OF ", "This is a test article. Cats are the best"),
("14 Days To A Better WASTE OF TIM", "This is a test article. Cats are the best"),
("What Make WASTE OF TIME Don't Wa", "This is a test article. Cats are the best"),
("Secrets To Getting WASTE OF TIME", "This is a test article. Cats are the best"),
("Use WASTE OF TIME To Make Someon", "This is a test article. Cats are the best"),
("At Last, The Secret To WASTE OF ", "This is a test article. Cats are the best"),
("5 Ways Of WASTE OF TIME That Can", "This is a test article. Cats are the best"),
("5 Romantic WASTE OF TIME Ideas", "This is a test article. Cats are the best"),
("Your Key To Success: WASTE OF TI", "This is a test article. Cats are the best"),
("3 Ways Twitter Destroyed My WAST", "This is a test article. Cats are the best"),
("Learn How To Start WASTE OF TIME", "This is a test article. Cats are the best"),
("What Is WASTE OF TIME and How Do", "This is a test article. Cats are the best"),
("Never Lose Your WASTE OF TIME Ag", "This is a test article. Cats are the best"),
("Avoid The Top 10 Mistakes Made B", "This is a test article. Cats are the best"),
("Top 3 Ways To Buy A Used WASTE O", "This is a test article. Cats are the best"),
("5 Ways WASTE OF TIME Will Help Y", "This is a test article. Cats are the best"),
("How To Save Money with WASTE OF ", "This is a test article. Cats are the best"),
("How To Make Your WASTE OF TIME L", "This is a test article. Cats are the best"),
("WASTE OF TIME And The Chuck Norr", "This is a test article. Cats are the best"),
("The Ultimate Guide To WASTE OF T", "This is a test article. Cats are the best"),
("Why WASTE OF TIME Succeeds", "This is a test article. Cats are the best"),
("Now You Can Have Your WASTE OF T", "This is a test article. Cats are the best"),
("How To Buy (A) WASTE OF TIME On ", "This is a test article. Cats are the best")
EOD;

$db->exec('INSERT INTO articles (name, content) VALUES' . $values);
